import Link from 'next/link';
import { SiteHeader } from '@/components/SiteHeader';
import { SiteFooter } from '@/components/SiteFooter';
import { ProcedureVisual } from '@/components/ProcedureVisual';
import { treatmentPagesEs } from '@/lib/treatments-es';
import type { TreatmentPageData } from '@/lib/treatments';
const whatsappBase='https://wa.me/526648816589?text=';
const pricing:Record<string,{label:string;price:string;detail:string;note:string}>={'dental-implants-tijuana':{label:'IMPLANTE DENTAL INDIVIDUAL',price:'$1,500 USD',detail:'Incluye implante, aditamento y corona final.',note:'Las necesidades y el costo final del tratamiento se confirman después de la valoración clínica y los estudios de imagen necesarios.'},'veneers-tijuana':{label:'CARILLAS',price:'$499 USD',detail:'Por carilla.',note:'Las necesidades y el costo final se confirman después de la valoración clínica.'},'dental-crowns-tijuana':{label:'CORONAS',price:'$450 USD',detail:'Por corona. El material se selecciona de acuerdo con las necesidades clínicas y estéticas de cada caso.',note:'Las necesidades y el costo final se confirman después de la valoración clínica.'},'general-dentistry-tijuana':{label:'PRIMERA VISITA',price:'$100 USD',detail:'Incluye valoración integral y radiografías necesarias.',note:'Pregunta por las promociones vigentes para pacientes de primera vez al momento de agendar.'}};
const conversion:Record<string,{eyebrow:string;headline:string;body:string;bullets:string[]}>={'dental-implants-tijuana':{eyebrow:'¿ESTÁS CONSIDERANDO UN IMPLANTE EN TIJUANA?',headline:'Empecemos por tu caso, no por venderte algo.',body:'Si ya tienes radiografías, tomografía/CBCT o un plan de tratamiento, envíanoslo. Podemos ayudarte a entender qué falta evaluar antes de que hagas el viaje.',bullets:['Atención en español e inglés','Planeación para pacientes locales y de EE.UU.','Secuencia clara antes de iniciar']},'all-on-4-tijuana':{eyebrow:'¿ARCADA SUPERIOR, INFERIOR O AMBAS?',headline:'Conoce el proceso completo antes de viajar.',body:'Una rehabilitación de arco completo es mucho más que colocar implantes. Planeamos la cirugía, la etapa provisional, cicatrización, restauración final y visitas de seguimiento como un solo caso coordinado.',bullets:['Planeación conjunta de ambas arcadas','Ruta de tres visitas en casos seleccionados','Podemos coordinar hospedaje']},'veneers-tijuana':{eyebrow:'¿ESTÁS PENSANDO EN CARILLAS?',headline:'Diseñemos la sonrisa antes de preparar los dientes.',body:'Envíanos fotografías claras de tu sonrisa y cualquier estudio reciente que tengas. Podemos empezar hablando de proporciones, posición dental, conservación del esmalte y del resultado que realmente buscas.',bullets:['Diseño de sonrisa natural','Planeación conservadora','Atención en español e inglés']}};
export function TreatmentPageEs({data}:{data:TreatmentPageData}){const d=treatmentPagesEs[data.slug]||data;const price=pricing[d.slug];const cv=conversion[d.slug];const whatsapp=`${whatsappBase}${encodeURIComponent(`Hola NONE32, me gustaría saber si ${d.navLabel} es adecuado para mi caso.`)}`;const related=Object.values(treatmentPagesEs).filter(x=>x.slug!==d.slug).slice(0,4);return <main className="treatment-page" lang="es">
<section className="treatment-hero"><SiteHeader language="es"/><div className="treatment-hero-grid"><div className="treatment-hero-copy"><p className="kicker gold">{d.number} · GUÍA DE TRATAMIENTO NONE32</p><h1>{d.displayTitle.split('\n').map((x,i)=><span key={x}>{x}{i===0&&<br/>}</span>)}</h1><p className="treatment-dek">{d.dek}</p><div className="button-row"><a className="button button-gold" href={whatsapp}>Escríbenos por WhatsApp <span>→</span></a><Link className="button button-clear" href="/es#treatments">Todos los tratamientos</Link></div>{cv&&<p className="treatment-response-note">¿Ya tienes radiografías, tomografía o un plan de tratamiento? Envíalo junto con tu mensaje.</p>}</div><ProcedureVisual type={d.visual}/></div><div className="treatment-facts">{d.heroFacts.map(f=><div key={f.label}><span>{f.label}</span><strong>{f.value}</strong></div>)}</div></section>
{price&&<section className="treatment-price-strip"><div><p className="kicker gold">{price.label}</p><span className="starting-at">Desde</span><strong>{price.price}</strong></div><div><p>{price.detail}</p><small>{price.note}</small><a className="button button-gold" href={whatsapp}>Pregunta por tu caso <span>→</span></a></div></section>}
{cv&&<section className="conversion-panel"><div><p className="kicker gold">{cv.eyebrow}</p><h2>{cv.headline}</h2><p>{cv.body}</p></div><div className="conversion-actions"><div className="conversion-bullets">{cv.bullets.map(x=><span key={x}>+ {x}</span>)}</div><a className="button button-gold" href={whatsapp}>Cuéntanos sobre tu caso <span>→</span></a></div></section>}
{d.slug==='all-on-4-tijuana'&&<section className="full-mouth-offer"><div className="full-mouth-price"><span>SUPERIOR + INFERIOR</span><strong>$25,000 <small>USD</small></strong><em>Para casos candidatos después de valoración clínica.</em></div><div><p className="kicker gold">UNA RUTA COMPLETA PARA AMBAS ARCADAS</p><h2>Un solo plan, desde la cirugía hasta los dientes finales.</h2><p>Para pacientes que necesitan rehabilitar ambas arcadas, NONE32 puede coordinar el tratamiento superior e inferior como un solo proceso planeado, en lugar de una serie de citas desconectadas.</p><div className="offer-grid"><span><b>01</b> Cirugía + etapa provisional</span><span><b>02</b> Cicatrización + registros finales</span><span><b>03</b> Entrega de restauraciones finales</span><span><b>+</b> Hospedaje coordinado para las visitas planeadas</span></div><p className="offer-disclaimer">El número de implantes, carga inmediata, injertos, diseño protésico y secuencia exacta de visitas dependen de la exploración, estudios de imagen, estabilidad y necesidades clínicas individuales. Tu plan de tratamiento por escrito define exactamente qué incluye tu caso.</p><a className="button button-gold" href={`${whatsappBase}${encodeURIComponent('Hola NONE32, me interesa la opción de $25,000 USD para rehabilitación superior e inferior. Quisiera saber si soy candidato.')}`}>Pregunta por la opción de $25,000 <span>→</span></a></div></section>}
<section className="treatment-intro-band"><p>Información clara. Limitaciones reales. Planeación individual.</p><strong>NO HAY DOS PACIENTES IGUALES.</strong></section>
<section className="treatment-sections">{d.sections.map((s,i)=><article className={`treatment-section ${i%2?'is-offset':''}`} key={s.title}><div className="treatment-section-index">{String(i+1).padStart(2,'0')}</div><div className="treatment-section-copy"><p className="kicker gold">{s.eyebrow}</p><h2>{s.title}</h2>{s.body.map(p=><p key={p}>{p}</p>)}{s.bullets&&<ul>{s.bullets.map(b=><li key={b}>{b}</li>)}</ul>}{s.note&&<div className="treatment-note">{s.note}</div>}</div></article>)}</section>
<section className="treatment-reality"><div><p className="kicker gold">EL ESTÁNDAR NONE32</p><h2>Entendemos por qué preguntas.</h2></div><div><p>Los pacientes no deberían tener que buscar en un grupo de Facebook para descubrir la pregunta que hubieran querido hacer antes del tratamiento. Nuestro objetivo es explicar el plan, las alternativas, las limitaciones y la secuencia esperada antes de que te comprometas.</p><p>Eso no significa que todos los resultados puedan garantizarse. Significa que la incertidumbre debe hablarse con honestidad y que el tratamiento debe construirse alrededor de la persona que tenemos enfrente.</p><strong>WE GET IT. WE GOT YOU.</strong></div></section>
<section className="review-proof"><div><p className="kicker gold">EXPERIENCIAS DE PACIENTES REALES</p><h2>No tienes que creerle a la página.</h2><p>Lee lo que nuestros pacientes dicen sobre su experiencia con NONE32 directamente en Google. Mantenemos las reseñas ahí para que puedas verlas en su contexto original, en lugar de seleccionarlas o reescribirlas aquí.</p></div><a className="button button-clear" href="https://www.google.com/maps/search/?api=1&query=NONE32+Tijuana" target="_blank" rel="noreferrer">Ver reseñas de NONE32 en Google <span>↗</span></a></section>
<section className="treatment-sources" aria-labelledby="evidence-title-es"><div><p className="kicker gold">EDUCACIÓN PARA PACIENTES BASADA EN EVIDENCIA</p><h2 id="evidence-title-es">Lee más allá del marketing.</h2><p>Estas páginas son material educativo para pacientes y no constituyen un diagnóstico. Las decisiones clínicas se toman después de una exploración y los registros apropiados. Referenciamos fuentes profesionales y científicas independientes para que puedas seguir informándote.</p></div><div className="source-links">{d.sources.map(s=><a href={s.href} key={s.href} target="_blank" rel="noreferrer"><span>{s.label}</span><b>↗</b></a>)}</div></section>
<section className="related-treatments"><p className="kicker gold">TRATAMIENTOS RELACIONADOS</p><div className="related-treatment-grid">{related.map(x=><Link href={`/es/treatments/${x.slug}`} key={x.slug}><span>{x.number}</span><strong>{x.navLabel}</strong><b>→</b></Link>)}</div></section>
<section className="treatment-cta"><div><p className="kicker gold">TU CASO ES EL SIGUIENTE PASO</p><h2>Primero información.<br/><em>Después, un plan.</em></h2></div><div><p>Envíanos tu pregunta, radiografías recientes o tu plan de tratamiento si ya lo tienes. Te diremos qué información hace falta antes de poder hacer una recomendación con sentido.</p><a className="button button-gold" href={whatsapp}>Escríbenos por WhatsApp <span>→</span></a></div></section><SiteFooter language="es"/></main>}
